
export const PALABRAS_ALEATORIAS = [
  // Lugares y Establecimientos
  "Playa", "Cine", "Hospital", "Escuela", "Fútbol", "Restaurante", "Aeropuerto", "Circo", "Museo", "Biblioteca", 
  "Montaña", "Parque de diversiones", "Zoológico", "Supermercado", "Gimnasio", "Estación de tren", "Hotel", "Banco",
  "Iglesia", "Farmacia", "Estadio", "Teatro", "Barco pirata", "Castillo", "Universidad", "Oficina", "Discoteca", 
  "Selva", "Desierto", "Laboratorio", "Cocina", "Baño", "Sótano", "Ático", "Ascensor", "Puente", "Túnel", 
  "Cueva", "Isla", "Volcán", "Granja", "Fábrica", "Cárcel", "Comisaría", "Bomberos", "Ambulancia", "Taxi", 
  "Autobús", "Avión", "Helicóptero", "Cohete", "Submarino", "Crucero", "Bicicleta", "Moto", "Patineta", 
  "Esquí", "Surf", "Tenis", "Baloncesto", "Voleibol", "Golf", "Boxeo", "Karate", "Yoga", "Pintura", 
  "Escultura", "Concierto", "Fiesta", "Boda", "Cumpleaños", "Cementerio", "Jardín", "Piscina", "Spa",
  "Casino", "Boliche", "Pista de hielo", "Ópera", "Catedral", "Mezquita", "Sinagoga", "Templo budista", "Rascacielos",
  "Faro", "Muelle", "Acuario", "Planetario", "Observatorio", "Refugio nuclear", "Búnker", "Trinchera", "Mansión",
  "Choza", "Iglú",  "Mercado", "Tianguis",
  "Centro comercial", "Peluquería", "Barbería", "Taller mecánico", "Gasolinera", "Lavandería", "Panadería", "Carnicería",
  "Ferretería", "Juguetería", "Floristería", "Librería", "Cafetería", "Bar", "Cantina", "Pub", "Viñedo",
  "Cervecería", "Fábrica de chocolate", "Central nuclear", "Presa", "Molino de viento", "Pozo petrolero", "Mina",
  "Cantera", "Vertedero", "Planta de reciclaje", "Orfanato", "Asilo", "Guardería", "Instituto", "Internado",
  "Campamento", "Parque nacional", "Reserva natural", "Sabana", "Tundra", "Glaciar", "Iceberg", 
  "Oasis", "Pantano", "Manglar", "Bosque encantado", "Casa embrujada", "OVNI", "Estación espacial", "Base lunar",
  "Marte", "Agujero negro", "Nube", "Arcoíris", "Tormenta", "Huracán", "Tornado", "Terremoto", "Tsunami",
  "Guerra", "Paz", "Paraíso", "Infierno", "Limbo", "Sueño", "Pesadilla", "Recuerdo", "Futuro",
  "Laberinto", "Sauna", "Jacuzzi", "Probador", "Escaparate", "Balcón", "Terraza", "Patio", "Garaje",

  // Nuevas 50 palabras añadidas
  "Satélite", "Caleidoscopio", "Burbuja", "Relámpago", "Sinfonía", "Acuarela", "Diamante", "Esmeralda", "Antorcha", 
  "Ámbar", "Carbón", "Grafitis", "Origami", "Ajedrez", "Parchís", "Ruleta", "Monopoly", "Cluedo", "Scrabble", 
  "Jenga", "Twister", "Dardos", "Billar", "Ping Pong", "Bádminton", "Tiro con arco", "Esgrima", "Remo", "Vela", 
  "Equitación", "Polo", "Críquet", "Rugby", "Balonmano", "Waterpolo", "Patinaje artístico", "Salto de trampolín", 
  "Gimnasia rítmica", "Halterofilia", "Lucha libre", "Sumo", "Aikido", "Capoeira", "Breakdance", "Ballet", 
  "Mosaico", "Cripta", "Catacumbas", "Gárgola", "Reliquia",

  // Animales
  "León", "Elefante", "Jirafa", "Pingüino", "Delfín", "Águila", "Serpiente", "Perro", "Gato", "Caballo",
  "Tigre", "Oso", "Lobo", "Zorro", "Conejo", "Canguro", "Koala", "Panda", "Gorila", "Mono", "Chimpancé",
  "Lemur", "Mapache", "Nutria", "Castor", "Ardilla", "Ratón", "Rata", "Hámster", 
  "Cerdo", "Vaca", "Toro", "Oveja", "Cabra", "Burro", "Mula", "Camello", "Llama",
  "Hipopótamo", "Rinoceronte", "Cebra", "Búfalo", 
  "Puma",
  "Armadillo", "Oso hormiguero", "Murciélago", "Ballena", "Orca",
  "Foca", "Búho", "Cuervo", 
  "Paloma", "Pelícano", "Cigüeña", "Cisne", "Pato", "Gallina", 
  "Pavo", "Pavo real", "Loro", "Periquito", "Canario", "Colibrí", "Pájaro carpintero", 
  "Tucán", "Avestruz", "Emú", "Kiwi", "Cocodrilo", "Caimán", "Tortuga", "Iguana", "Camaleón", "Gecko", 
  "Víbora","Rana", 
  "Tiburón", "Raya","Atún",
  "Pulpo","Cangrejo",
   "Camarón", "Mariposa", "Abeja", "Hormiga",  
  "Mariquita", "Saltamontes", "Grillo", "Cucaracha", "Mosca", "Mosquito",  
  "Araña", "Escorpión", 

  // Comida
  "Pizza", "Sushi", "Hamburguesa", "Hot dog", "Sandwich", "Tacos", "Burrito", "Quesadilla", "Enchiladas", "Pozole",
  "Tamales",  "Espagueti", "Lasaña",
  "Pollo frito", "Alitas",  "Ramen", "Ceviche", "Empanadas", "Arepas",  "Crepas", "Waffles",
  "Manzana", "Banana", "Naranja", "Uva", "Fresa", "Cereza", "Sandía", "Melón", "Piña", "Mango", "Papaya",
  "Kiwi", "Limón", "Lima", "Aguacate", "Tomate", "Lechuga", "Espinaca", "Zanahoria", "Papa", "Cebolla",
  "Ajo", "Champiñón", "Brócoli", "Coliflor", "Maíz", "Pepino", "Calabaza", "Berenjena", "Pimiento",
  "Helado", "Chocolate", "Pastel", "Tarta", "Galletas", "Brownie", "Muffin", "Donas", "Churros", "Flan",
  "Gelatina", "Tiramisú", "Cheesecake", "Croissant", "Pan dulce", "Miel",
  "Mermelada", "Nutella", "Cajeta", "Dulce de leche", "Caramelos", "Chicle", "Paleta", "Bombones",
  "Café", "Té", "Leche", "Jugo", "Refresco", "Agua", "Vino", "Cerveza", "Tequila", "Mezcal", "Whisky",
  "Vodka", "Ron", "Aceite", "Vinagre", "Sal", "Pimienta", "Azúcar", "Harina", "Huevo", "Queso", 

  // Lugares (ciudades, países, maravillas)
  "París",  "Ciudad de México","Egipto", "Francia", "Italia", "España", "Alemania", "Japón", "China", "Brasil", "Argentina",
  "México", "Estados Unidos", "Canadá", "Australia", "Rusia", "India",
  "La Luna", "Marte", "El Sol", "Polo Norte", "Polo Sur", "Monte Everest", "Torre Eiffel", "Estatua de la Libertad", "Muralla China", "Antártida", "Volcán", "Cueva", "Isla desierta", "Selva", "Bosque",

  // Oficios / Profesiones
  "Médico", "Enfermero", "Cirujano", "Dentista", "Veterinario", "Psicólogo", "Farmacéutico", "Científico",
  "Ingeniero", "Arquitecto", "Abogado", "Juez", "Fiscal", "Policía", "Detective", "Espía", "Militar",
  "Bombero", "Paramédico", "Rescatista", "Piloto", "Azafata", "Astronauta", "Capitán", "Marinero",
  "Conductor", "Taxista", "Camionero", "Maquinista", "Profesor", "Maestro", "Bibliotecario", "Historiador",
  "Arqueólogo", "Periodista", "Reportero", "Fotógrafo", "Escritor", "Poeta", "Traductor", "Diseñador",
  "Programador", "Hacker", "Gamer", "Youtuber", "Influencer", "Actor", "Director", "Cantante", "Músico",
  "Compositor", "Bailarín", "Pintor", "Escultor", "Modelo", "Chef", "Cocinero", "Panadero", "Pastelero",
  "Camarero", "Agricultor", "Granjero", "Ganadero", "Pescador", "Jardinero",
  "Florista", "Carpintero", "Fontanero", "Electricista", "Mecánico", "Albañil", "Soldador", "Minero",
  "Sastre", "Zapatero", "Relojero", "Joyero", "Peluquero", "Maquillador", "Tatuador", "Masajista",
  "Entrenador", "Árbitro", "Deportista", "Político", "Presidente", "Rey", "Reina", "Príncipe", "Princesa",
  "Sacerdote", "Monja", "Papa", "Mago", "Payaso", "Mimo", "Acróbata", "Ladrón", "Pirata", "Ninja", "Samurái",

  // Objetos
  "Reloj", "Teléfono", "Gafas", "Llave", "Cartera", "Moneda", "Billete", "Tarjeta", "Pasaporte", "Mapa",
  "Libro", "Cuaderno", "Lápiz", "Bolígrafo", "Goma", "Tijeras", "Regla", "Pegamento", "Mochila", "Maleta",
  "Silla", "Mesa", "Sofá", "Cama", "Almohada", "Manta", "Armario", "Espejo", "Lámpara", "Vela",
  "Cuchara", "Tenedor", "Cuchillo", "Plato", "Vaso", "Taza", "Olla", "Sartén", "Microondas", "Refrigerador",
  "Lavadora", "Plancha", "Aspiradora", "Escoba", "Trapeador", "Cubo", "Esponja", "Jabón", "Champú",
  "Cepillo de dientes", "Pasta dental", "Peine", "Toalla", "Papel higiénico", "Perfume", "Maquillaje",
  "Camisa", "Camiseta", "Pantalón", "Vestido", "Falda", "Abrigo", "Chamarra", "Suéter", "Calcetines",
  "Zapatos", "Zapatillas", "Botas", "Sandalias", "Sombrero", "Gorra", "Bufanda", "Guantes", "Cinturón",
  "Corbata", "Collar", "Anillo", "Pulsera", "Pendientes", "Paraguas",
  "Computadora", "Laptop", "Tablet", "Teclado", "Ratón", "Pantalla", "Impresora", "Cámara", "Televisión",
  "Radio", "Altavoz", "Auriculares", "Micrófono", "Batería", "Cargador", "Cable", "USB",
  "Martillo", "Destornillador", "Clavo", 
  "Escalera", "Linterna", "Brújula", "Prismáticos", "Telescopio", "Microscopio",
  "Guitarra", "Piano", "Violín", "Tambor", "Flauta", "Trompeta", "Balón", "Pelota", "Raqueta", "Bate",
  "Casco", "Espada", "Escudo", "Arco", "Flecha", "Pistola", "Cañón", "Bomba", "Bandera", "Trofeo", "Medalla", "Ventilador", "Aire acondicionado", "Calefactor", "Termómetro", "Calendario", "Cuadro", "Marco de fotos", "Cortina", "Persiana", "Alfombra",
"Tapete", "Basurero", "Bolsa de basura", "Abrelatas", "Sacacorchos", "Rallador", "Colador", "Tabla de cortar", "Batidora", "Licuadora",
"Cafetera", "Tostadora", "Exprimidor", "Horno", "Estufa", "Servilleta",
"Mantel", "Jarra", "Termo", "Botella", "Hielera", "Molde", "Papel aluminio", "Guante de cocina", "Manopla", "Trapo", "Recogedor", "Fregadero", 
"Inodoro", "Tapa del inodoro", "Portacepillos", "Jabonera", "Dispensador", "Cortauñas", "Rasuradora", "Secadora de cabello", "Plancha de cabello", "Cepillo",
 "Colchón",  "Carpeta",
"Sobre", "Calculadora", "Engrapadora", "Cinta adhesiva", "Corrector", "Marcador", "Pizarrón",
"Borrador", "Portaminas", "Sacapuntas", "Regadera", "Manguera", "Maceta",
"Guantes de jardinería", "Pala", "Rastrillo", "Enchufe", "Detector de humo", "Reloj despertador", "Cronómetro", "Temporizador", "Báscula", "Candado",
"Timbre","Control remoto", "Reproductor DVD", "Consola de videojuegos",
 "Organizador", "Caja", "Caja fuerte", 
"Garrafón", "Espátula","Tupper", 
"Cloro", "Matamoscas", "Repelente",
 "Álbum de fotos", "Reloj de pared", "Campana", "Imán"


];

export const TEMAS = {
  ANIMALES: [
    "León", "Elefante", "Jirafa", "Pingüino", "Delfín", "Águila", "Serpiente", "Perro", "Gato", "Caballo",
    "Tigre", "Oso", "Lobo", "Zorro", "Conejo", "Canguro", "Koala", "Panda", "Gorila", "Mono", "Chimpancé",
    "Lemur", "Mapache", "Tejón", "Nutria", "Castor", "Ardilla", "Ratón", "Rata", "Hámster", "Cuy",
    "Cerdo", "Vaca", "Toro", "Oveja", "Cabra", "Burro", "Mula", "Camello", "Dromedario", "Llama", "Alpaca",
    "Hipopótamo", "Rinoceronte", "Cebra", "Búfalo", "Bisonte", "Alce", "Ciervo", "Gacela", "Antílope",
    "Guepardo", "Leopardo", "Jaguar", "Puma", "Lince", "Hiena", "Mangosta", "Ornitorrinco",
    "Equidna", "Armadillo", "Perezoso", "Oso hormiguero", "Murciélago", "Ballena", "Orca", "Cachalote", "Narval",
    "Foca", "León marino", "Morsa", "Manatí", "Búho", "Lechuza", "Halcón", "Cóndor", "Buitre", "Cuervo", 
    "Paloma", "Gaviota", "Pelícano", "Cigüeña", "Flamenco", "Cisne", "Pato", "Ganso", "Gallina", "Gallo", 
    "Pavo", "Pavo real", "Loro", "Guacamayo", "Cacatúa", "Periquito", "Canario", "Colibrí", "Pájaro carpintero", 
    "Tucán", "Avestruz", "Emú", "Kiwi", "Cocodrilo", "Caimán", "Tortuga", "Iguana", "Camaleón", "Gecko", 
    "Dragón de Komodo", "Cobra", "Pitón", "Boa", "Víbora", "Cascabel", "Rana", "Sapo", "Salamandra", "Ajolote",
    "Tiburón", "Raya", "Manta", "Pez payaso", "Pez espada", "Atún", "Salmón", "Trucha", "Carpa", "Piraña",
    "Anguila", "Caballito de mar", "Pulpo", "Calamar", "Medusa", "Estrella de mar", "Erizo de mar", "Cangrejo",
    "Langosta", "Camarón", "Ostra", "Almeja", "Mariposa", "Abeja", "Avispa", "Hormiga", "Termita", "Escarabajo", 
    "Mariquita", "Saltamontes", "Grillo", "Cucaracha", "Mosca", "Mosquito", "Libélula", "Mantis religiosa", 
    "Araña", "Tarántula", "Escorpión", "Ciempiés",
  ],
  COMIDA: [
    "Tacos", "Quesadillas", "Tortas", "Tamales", "Enchiladas", "Chilaquiles",
    "Pozole", "Menudo", "Sopa", "Caldo", "Arroz", "Frijoles",
    "Carne asada", "Pollo asado", "Pescado", "Mariscos",
    "Guisado", "Mole", "Chiles rellenos", "Tostadas",
    "Flautas", "Gorditas", "Sopes", "Pambazo",
    "Elote", "Esquites", "Nopales", "Guacamole",
    "Pan dulce", "Postre", "Atole", "Agua fresca",
    "Manzana", "Banana", "Naranja", "Uva", "Fresa", "Cereza", "Sandía", "Melón", "Piña", "Mango", "Papaya",
    "Kiwi", "Limón", "Lima", "Aguacate", "Tomate", "Lechuga", "Espinaca", "Zanahoria", "Papa", "Cebolla",
    "Ajo", "Champiñón", "Brócoli", "Coliflor", "Maíz", "Pepino", "Calabaza", "Pimiento",
    "Helado", "Chocolate", "Pastel", "Galletas", "Brownie", "Muffin", "Donas", "Churros", "Flan",
    "Gelatina", "Pudín", "Mousse", "Tiramisú", "Cheesecake", "Macarons", "Croissant", "Pan dulce", "Miel",
    "Mermelada", "Nutella", "Cajeta", "Dulce de leche", "Caramelos", "Chicle", "Paleta", "Bombones",
    "Café", "Té", "Leche", "Jugo", "Refresco", "Agua", "Vino", "Cerveza", "Tequila", "Mezcal", "Whisky",
    "Vodka", "Ron", "Coctel", "Batido", "Aceite", "Vinagre", "Sal", "Pimienta", "Azúcar", "Harina", "Huevo", "Queso", "Yogur"
  ],
  LUGARES: [
    "París",  "Ciudad de México","Egipto", "Francia", "Italia", "España", "Alemania", "Japón", "China", "Brasil", "Argentina",
    "México", "Estados Unidos", "Canadá", "Australia", "Rusia", "India",
    "La Luna", "Marte", "El Sol", "Polo Norte", "Polo Sur", "Monte Everest", "Torre Eiffel", "Estatua de la Libertad", "Muralla China", "Antártida", "Volcán", "Cueva", "Isla desierta", "Selva", "Bosque",
  ],
  OFICIOS: [
    "Médico", "Enfermero", "Cirujano", "Dentista", "Veterinario", "Psicólogo", "Farmacéutico", "Científico",
    "Ingeniero", "Arquitecto", "Abogado", "Juez", "Fiscal", "Policía", "Detective", "Espía", "Militar",
    "Bombero", "Paramédico", "Rescatista", "Piloto", "Azafata", "Astronauta", "Capitán", "Marinero",
    "Conductor", "Taxista", "Camionero", "Maquinista", "Profesor", "Maestro", "Bibliotecario", "Historiador",
    "Arqueólogo", "Periodista", "Reportero", "Fotógrafo", "Escritor", "Poeta", "Traductor", "Diseñador",
    "Programador", "Hacker", "Gamer", "Youtuber", "Influencer", "Actor", "Director", "Cantante", "Músico",
    "Compositor", "Bailarín", "Pintor", "Escultor", "Modelo", "Chef", "Cocinero", "Panadero", "Pastelero",
    "Camarero", "Barman", "Sumiller", "Agricultor", "Granjero", "Ganadero", "Pescador", "Jardinero",
    "Florista", "Carpintero", "Fontanero", "Electricista", "Mecánico", "Albañil", "Soldador", "Minero",
    "Sastre", "Zapatero", "Relojero", "Joyero", "Peluquero", "Maquillador", "Tatuador", "Masajista",
    "Entrenador", "Árbitro", "Deportista", "Político", "Presidente", "Rey", "Reina", "Príncipe", "Princesa",
    "Sacerdote", "Monja", "Papa", "Mago", "Payaso", "Mimo", "Acróbata", "Ladrón", "Pirata", "Ninja", "Samurái"
  ],
  OBJETOS: [
    "Reloj", "Teléfono", "Gafas", "Llave", "Cartera", "Moneda", "Billete", "Tarjeta", "Pasaporte", "Mapa",
    "Libro", "Cuaderno", "Lápiz", "Bolígrafo", "Goma", "Tijeras", "Regla", "Pegamento", "Mochila", "Maleta",
    "Silla", "Mesa", "Sofá", "Cama", "Almohada", "Manta", "Armario", "Espejo", "Lámpara", "Vela",
    "Cuchara", "Tenedor", "Cuchillo", "Plato", "Vaso", "Taza", "Olla", "Sartén", "Microondas", "Refrigerador",
    "Lavadora", "Plancha", "Aspiradora", "Escoba", "Trapeador", "Cubo", "Esponja", "Jabón", "Champú",
    "Cepillo de dientes", "Pasta dental", "Peine", "Toalla", "Papel higiénico", "Perfume", "Maquillaje",
    "Camisa", "Camiseta", "Pantalón", "Vestido", "Falda", "Abrigo", "Chamarra", "Suéter", "Calcetines",
    "Zapatos", "Zapatillas", "Botas", "Sandalias", "Sombrero", "Gorra", "Bufanda", "Guantes", "Cinturón",
    "Corbata", "Collar", "Anillo", "Pulsera", "Pendientes", "Paraguas",
    "Computadora", "Laptop", "Tablet", "Teclado", "Ratón", "Pantalla", "Impresora", "Cámara", "Televisión",
    "Radio", "Altavoz", "Auriculares", "Micrófono", "Batería", "Cargador", "Cable", "USB", "Disco duro",
    "Martillo", "Destornillador", "Taladro", "Sierra", "Llave inglesa", "Clavo", "Tornillo", "Tuerca",
    "Escalera", "Linterna", "Brújula", "Prismáticos", "Telescopio", "Microscopio",
    "Guitarra", "Piano", "Violín", "Tambor", "Flauta", "Trompeta", "Balón", "Pelota", "Raqueta", "Bate",
    "Casco", "Espada", "Escudo", "Arco", "Flecha", "Pistola", "Cañón", "Bomba", "Bandera", "Trofeo", "Medalla"
  ],
  VIDEOJUEGOS: [
    "Super Mario Bros", "Pac-Man", "Tetris", "Minecraft", "Pokémon", 
    "Mario Kart", "Sonic the Hedgehog", "Donkey Kong", "Grand Theft Auto (GTA)",
    "Just Dance", "Guitar Hero", "Wii Sports", "Street Fighter", 
    "Mortal Kombat", "FIFA", "Super Smash Bros",
    "Candy Crush", "Angry Birds", "Plants vs Zombies", "Among Us", 
    "Fortnite", "Call of Duty", "Clash Royale", "Free Fire",
    "Crash Bandicoot", "The Sims", "Tomb Raider (Lara Croft)", 
    "Resident Evil", "God of War (Kratos)", "Halo"
  ],
  ADULTOS: [
    "Corrida", "Facial", "Garganta", "Anal", "Squirt", "Creampie", "Bukkake", "Gangbang", "Fisting", "Rimjob", "Dildo", "Plug", "Azotes", "Látigo", "Asfixia", "Cuckold", "Paja", "69", "Ano", "Polla", "Coño", "Tragar", "Gloryhole", "Orgía", "Doble", "Sexting", "Dickpic", "Nudes", "Webcam", "Incesto", "Violación", "Próstata", "Bodyshot", "Resaca", "Tatuaje", "Motel", "Lencería", "Juguetes", "Fetiche", "Besonegro", "Chupetón", "Esposas", "Antifaz", "Lubricante", "Condón", "Embarazo", "Viagra", "Leche", "Chorro", "Cornudo", "Puta", "Zorra", "Mamada", "Follada", "Culo", "Tetas", "Clítoris", "Prostituta", "Porno", "Gemidos", "Nalgadas", "Sumiso", "Ama", "Esclavo", "Cagar", "Mear", "Pedo", "Sudor", "Axila", "Pies", "Regla", "Flujo", "Roto", "Sida", "Gonorrea", "Herpes", "Embarazada", "Aborto", "Cojida", "Verga", "Maricón", "Travesti", "Shemale", "Transexual"
  ]
};

export const MIN_JUGADORES = 3;
export const MAX_JUGADORES = 16;
